/*
* generated by Xtext
*/
package org.arz.ui.contentassist.antlr;

import java.util.Collection;
import java.util.Map;
import java.util.HashMap;

import org.antlr.runtime.RecognitionException;
import org.eclipse.xtext.AbstractElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.AbstractContentAssistParser;
import org.eclipse.xtext.ui.editor.contentassist.antlr.FollowElement;
import org.eclipse.xtext.ui.editor.contentassist.antlr.internal.AbstractInternalContentAssistParser;

import com.google.inject.Inject;

import org.arz.services.MiniScriptGrammarAccess;

public class MiniScriptParser extends AbstractContentAssistParser {
	
	@Inject
	private MiniScriptGrammarAccess grammarAccess;
	
	private Map<AbstractElement, String> nameMappings;
	
	@Override
	protected org.arz.ui.contentassist.antlr.internal.InternalMiniScriptParser createParser() {
		org.arz.ui.contentassist.antlr.internal.InternalMiniScriptParser result = new org.arz.ui.contentassist.antlr.internal.InternalMiniScriptParser(null);
		result.setGrammarAccess(grammarAccess);
		return result;
	}
	
	@Override
	protected String getRuleName(AbstractElement element) {
		if (nameMappings == null) {
			nameMappings = new HashMap<AbstractElement, String>() {
				private static final long serialVersionUID = 1L;
				{
					put(grammarAccess.getExpressionAccess().getAlternatives(), "rule__Expression__Alternatives");
					put(grammarAccess.getBodyAccess().getAlternatives(), "rule__Body__Alternatives");
					put(grammarAccess.getFunctorAccess().getAlternatives(), "rule__Functor__Alternatives");
					put(grammarAccess.getNumExprTailAccess().getOperatorAlternatives_0_0(), "rule__NumExprTail__OperatorAlternatives_0_0");
					put(grammarAccess.getFactorTailAccess().getOperatorAlternatives_0_0(), "rule__FactorTail__OperatorAlternatives_0_0");
					put(grammarAccess.getTermAccess().getAlternatives(), "rule__Term__Alternatives");
					put(grammarAccess.getProgramAccess().getGroup(), "rule__Program__Group__0");
					put(grammarAccess.getProgramAccess().getGroup_2(), "rule__Program__Group_2__0");
					put(grammarAccess.getFunctionDeclarationAccess().getGroup(), "rule__FunctionDeclaration__Group__0");
					put(grammarAccess.getFunctionDeclarationAccess().getGroup_2(), "rule__FunctionDeclaration__Group_2__0");
					put(grammarAccess.getFunctionDeclarationAccess().getGroup_2_1(), "rule__FunctionDeclaration__Group_2_1__0");
					put(grammarAccess.getBodyAccess().getGroup_1(), "rule__Body__Group_1__0");
					put(grammarAccess.getBodyAccess().getGroup_1_2(), "rule__Body__Group_1_2__0");
					put(grammarAccess.getApplyAccess().getGroup(), "rule__Apply__Group__0");
					put(grammarAccess.getApplyAccess().getGroup_1(), "rule__Apply__Group_1__0");
					put(grammarAccess.getApplyTailAccess().getGroup(), "rule__ApplyTail__Group__0");
					put(grammarAccess.getApplyTailAccess().getGroup_2(), "rule__ApplyTail__Group_2__0");
					put(grammarAccess.getApplyTailAccess().getGroup_2_1(), "rule__ApplyTail__Group_2_1__0");
					put(grammarAccess.getNumericExpressionAccess().getGroup(), "rule__NumericExpression__Group__0");
					put(grammarAccess.getNumericExpressionAccess().getGroup_1(), "rule__NumericExpression__Group_1__0");
					put(grammarAccess.getNumExprTailAccess().getGroup(), "rule__NumExprTail__Group__0");
					put(grammarAccess.getFactorAccess().getGroup(), "rule__Factor__Group__0");
					put(grammarAccess.getFactorAccess().getGroup_1(), "rule__Factor__Group_1__0");
					put(grammarAccess.getFactorTailAccess().getGroup(), "rule__FactorTail__Group__0");
					put(grammarAccess.getVariableAssignmentAccess().getGroup(), "rule__VariableAssignment__Group__0");
					put(grammarAccess.getParenthesisExpressionAccess().getGroup(), "rule__ParenthesisExpression__Group__0");
					put(grammarAccess.getProgramAccess().getExpressionsAssignment_0(), "rule__Program__ExpressionsAssignment_0");
					put(grammarAccess.getProgramAccess().getExpressionsAssignment_2_0(), "rule__Program__ExpressionsAssignment_2_0");
					put(grammarAccess.getFunctionDeclarationAccess().getParametersAssignment_2_0(), "rule__FunctionDeclaration__ParametersAssignment_2_0");
					put(grammarAccess.getFunctionDeclarationAccess().getParametersAssignment_2_1_1(), "rule__FunctionDeclaration__ParametersAssignment_2_1_1");
					put(grammarAccess.getFunctionDeclarationAccess().getBodyAssignment_4(), "rule__FunctionDeclaration__BodyAssignment_4");
					put(grammarAccess.getBodyAccess().getExpressionsAssignment_0(), "rule__Body__ExpressionsAssignment_0");
					put(grammarAccess.getBodyAccess().getExpressionsAssignment_1_2_0(), "rule__Body__ExpressionsAssignment_1_2_0");
					put(grammarAccess.getApplyAccess().getArgumentsAssignment_1_1(), "rule__Apply__ArgumentsAssignment_1_1");
					put(grammarAccess.getApplyTailAccess().getArgumentsAssignment_2_0(), "rule__ApplyTail__ArgumentsAssignment_2_0");
					put(grammarAccess.getApplyTailAccess().getArgumentsAssignment_2_1_1(), "rule__ApplyTail__ArgumentsAssignment_2_1_1");
					put(grammarAccess.getApplyTailAccess().getNextCallAssignment_4(), "rule__ApplyTail__NextCallAssignment_4");
					put(grammarAccess.getLiteralExprAccess().getValueAssignment(), "rule__LiteralExpr__ValueAssignment");
					put(grammarAccess.getSymbolReferenceAccess().getIdAssignment(), "rule__SymbolReference__IdAssignment");
					put(grammarAccess.getNumericExpressionAccess().getNumExprTailAssignment_1_1(), "rule__NumericExpression__NumExprTailAssignment_1_1");
					put(grammarAccess.getNumExprTailAccess().getOperatorAssignment_0(), "rule__NumExprTail__OperatorAssignment_0");
					put(grammarAccess.getNumExprTailAccess().getFactorAssignment_1(), "rule__NumExprTail__FactorAssignment_1");
					put(grammarAccess.getNumExprTailAccess().getExprTailAssignment_2(), "rule__NumExprTail__ExprTailAssignment_2");
					put(grammarAccess.getFactorAccess().getFactorTailAssignment_1_1(), "rule__Factor__FactorTailAssignment_1_1");
					put(grammarAccess.getFactorTailAccess().getOperatorAssignment_0(), "rule__FactorTail__OperatorAssignment_0");
					put(grammarAccess.getFactorTailAccess().getTermAssignment_1(), "rule__FactorTail__TermAssignment_1");
					put(grammarAccess.getFactorTailAccess().getFactorTailAssignment_2(), "rule__FactorTail__FactorTailAssignment_2");
					put(grammarAccess.getVariableAssignmentAccess().getIdAssignment_0(), "rule__VariableAssignment__IdAssignment_0");
					put(grammarAccess.getVariableAssignmentAccess().getExpressionAssignment_2(), "rule__VariableAssignment__ExpressionAssignment_2");
				}
			};
		}
		return nameMappings.get(element);
	}
	
	@Override
	protected Collection<FollowElement> getFollowElements(AbstractInternalContentAssistParser parser) {
		try {
			org.arz.ui.contentassist.antlr.internal.InternalMiniScriptParser typedParser = (org.arz.ui.contentassist.antlr.internal.InternalMiniScriptParser) parser;
			typedParser.entryRuleModel();
			return typedParser.getFollowElements();
		} catch(RecognitionException ex) {
			throw new RuntimeException(ex);
		}		
	}
	
	@Override
	protected String[] getInitialHiddenTokens() {
		return new String[] { "RULE_WS", "RULE_ML_COMMENT", "RULE_SL_COMMENT" };
	}
	
	public MiniScriptGrammarAccess getGrammarAccess() {
		return this.grammarAccess;
	}
	
	public void setGrammarAccess(MiniScriptGrammarAccess grammarAccess) {
		this.grammarAccess = grammarAccess;
	}
}
