/*
* generated by Xtext
*/
package org.arz;

import org.eclipse.xtext.junit4.IInjectorProvider;

import com.google.inject.Injector;

public class MiniScriptUiInjectorProvider implements IInjectorProvider {
	
	public Injector getInjector() {
		return org.arz.ui.internal.MiniScriptActivator.getInstance().getInjector("org.arz.MiniScript");
	}
	
}
