/*
* generated by Xtext
*/
package org.arz.ui.outline;

import org.eclipse.xtext.ui.editor.outline.impl.DefaultOutlineTreeProvider;

/**
 * customization of the default outline structure
 * 
 */
public class MiniScriptOutlineTreeProvider extends DefaultOutlineTreeProvider {
	
}
