/*
 * generated by Xtext
 */
package org.arz.ui;

import org.eclipse.ui.plugin.AbstractUIPlugin;

/**
 * Use this class to register components to be used within the IDE.
 */
public class MiniScriptUiModule extends org.arz.ui.AbstractMiniScriptUiModule {
	public MiniScriptUiModule(AbstractUIPlugin plugin) {
		super(plugin);
	}
}
