/*
* generated by Xtext
*/
package org.arz.ui.contentassist;

/**
 * see http://www.eclipse.org/Xtext/documentation/latest/xtext.html#contentAssist on how to customize content assistant
 */
public class MiniScriptProposalProvider extends AbstractMiniScriptProposalProvider {

}
